name: Build & Deploy Jekyll (with plugins)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for jekyll-last-modified-at to access git history
      - uses: actions/configure-pages@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build --trace
      - name: Proof HTML
        uses: anishathalye/proof-html@v2
        with:
          directory: ./_site
          allow_missing_href: true
          enforce_https: true
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          ignore_url_re: |
            ^mailto:
            ^tel:
            https://fonts.googleapis.com/.*
            https://fonts.gstatic.com/.*
            ^https://twitter.com/.*
            ^https://x.com/.*
            ^https://bsky.app/.*
            ^https://mastodon.gamedev.place/.*
            ^https://facebook.com/.*
            ^https://www.facebook.com/.*
            ^https://t.me/.*
            ^https://gist.github.com/.*
            ^https://www.linkedin.com/.*
            ^https://linkedin.com/.*
            ^https://in.linkedin.com/.*
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
